language: generic

services:
  - docker

before_install:
  - docker build --build-arg GITHUB_PAT=${GITHUB_PAT} -t hnskde/tmongr-base-r .
  - docker run -d -ti --name tmongr-base-r hnskde/tmongr-base-r

script:
  - docker ps | grep -q tmongr-base-r

deploy:
  - provider: script
    script: bash docker_push.sh
    skip_cleanup: true
    on:
      branch: master

